CREATE DATABASE [$(dbName)]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'$(dbName)', FILENAME = N'$(dataPath)\$(dbName).mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON
( NAME = N'$(dbName)_log', FILENAME = N'$(dataPath)\$(dbName)_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [$(dbName)] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [$(dbName)] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [$(dbName)] SET ANSI_NULLS OFF
GO
ALTER DATABASE [$(dbName)] SET ANSI_PADDING OFF
GO
ALTER DATABASE [$(dbName)] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [$(dbName)] SET ARITHABORT OFF
GO
ALTER DATABASE [$(dbName)] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [$(dbName)] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [$(dbName)] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [$(dbName)] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [$(dbName)] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [$(dbName)] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [$(dbName)] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [$(dbName)] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [$(dbName)] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [$(dbName)] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [$(dbName)] SET  DISABLE_BROKER
GO
ALTER DATABASE [$(dbName)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [$(dbName)] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [$(dbName)] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [$(dbName)] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [$(dbName)] SET  READ_WRITE
GO
ALTER DATABASE [$(dbName)] SET RECOVERY SIMPLE
GO
ALTER DATABASE [$(dbName)] SET  MULTI_USER
GO
ALTER DATABASE [$(dbName)] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [$(dbName)] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO
ALTER DATABASE [$(dbName)] SET DELAYED_DURABILITY = DISABLED
GO
USE [$(dbName)]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [$(dbName)] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
